---
name: Slapper
author: jojoe77777
version: 1.5.0
description: Slapper, the NPC plugin for PocketMine-MP
main: slapper\Main
api:
- 3.9.0
mcpe-protocol:
- 361
website: https://github.com/jojoe77777/Slapper
commands:
  slapper:
    description: Create a Slapper NPC, or edit an existing one!
    usage: /slapper [args]...
    permission: slapper.command
  rca:
    description: Execute a command as someone else!
    usage: /rca <player> <command>
    permission: slapper.rca
  nothing:
    description: Do nothing!
    usage: /nothing
    permission: slapper.nothing
permissions:
  slapper:
    description: Allow using all Slapper commands
    default: false
    children:
      slapper.command:
        description: Allow using /slapper
        default: false
      slapper.create:
        description: Allow using command /slapper create
        default: false
      slapper.edit:
        description: Allow editing Slapper entity data with /slapper edit
        default: false
      slapper.nothing:
        description: Allow doing nothing
        default: false
      slapper.rca:
        description: Allow running commands as other players
        default: false
      slapper.remove:
        description: Allow removing Slapper entities with /slapper remove [id]
        default: false
      slapper.id:
        description: Allow viewing entity ID
        default: false
      slapper.help:
        description: Allow viewing Slapper help page
        default: false
...
