---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "§l§6●§d▬▬ §d【§bмιɴᴇ§aғoʀᴇ§6 ☭ §csκʏʙʟocκ§d】 ▬▬§6●§c"
OutdatedClient:
  custom: false
  message: "&cYour MCPE client is outdated!"
OutdatedServer:
  custom: false
  message: "&cOops! Server outdated!"
WhitelistedServer:
  custom: true
  message: "&l&6[&c✱&6]&r &c Server Update!"
FullServer:
  custom: true
  message: "&e{PLAYER}&b, The Server is full &c[{TOTALPLAYERS}/{MAXPLAYERS}]&b!\n&l&dTry to join later :)"
FirstJoin:
  enable: true
  message: "&l&e【&d{PLAYER}&e】 &eGia Nhập Server Lần Đầu &l&a٩(^‿^)۶"
Join:
  hide: false
  custom: true
  message: "&l&e【&d{PLAYER}&e】&b Đã tham gia máy chủ &l&a=^.^="
Quit:
  hide: false
  custom: true
  message: "&l&e【&d{PLAYER}&e】&b Đã thoát khỏi máy chủ &av(ಥ ̯ ಥ)v"
WorldChange:
  enable: false
  message: "&l&e【&d{PLAYER}&e】&b di chuyển từ &1{ORIGIN}&e tới &b{TARGET}"
Death:
  hide: false
  custom: true
  message: "&l&e【&d{PLAYER}&e】&b đã ra đi mãi mãi &a(╥﹏╥)"
  death-contact-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã bị chết bởi &c{BLOCK}&a (╥﹏╥)"
  kill-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã bị sát hại&a (╥﹏╥)"
  death-projectile-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b bị bắn headshot bởi &c{KILLER}&a (╥﹏╥)"
  death-suffocation-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã rìa đời do ko bít bơi XD&a (╥﹏╥)"
  death-fall-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã tự tử do bị gấu bỏ...&a (ಠ_ರೃ)"
  death-fire-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b do trời quá nóng nên đã tắm trong lava&a (ಠ_ರೃ)"
  death-on-fire-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã bị thiêu cháy&a (ಠ_ರೃ)"
  death-lava-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b do trời quá nóng nên đã tắm trong lava&a ●﹏●"
  death-drowning-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b chết đuôi, Ăn hành&a ●﹏●"
  death-explosion-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã bị ăn c4&a (●´ω｀●)"
  death-void-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã lạc trôi vào vũ trụ&a (●´ω｀●)"
  death-suicide-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b Đang Thảm du&a ●﹏●"
  death-magic-message:
    hide: false
    custom: true
    message: "&l&e【&d{PLAYER}&e】&b đã chết do uống thuốc độc&a (●´ω｀●)"
...
