---
Positions:
- world: skyblock
  x: -363
  "y": 68
  z: 405
Update-Interval: 60
Header: §l§6● §dTop§c Đảo §bMine§aFore§6 ●
text: |-
  §c§l↣ §f[§cTOP 1§f] §r§btycitra:§a 101 lv
  §c§l↣ §f[§cTOP 2§f] §r§bconsulartag7466:§a 86 lv
  §c§l↣ §f[§cTOP 3§f] §r§blongpro2205:§a 83 lv
  §c§l↣ §f[§cTOP 4§f] §r§bherobrine130624:§a 75 lv
  §c§l↣ §f[§cTOP 5§f] §r§bbinhcute2467:§a 69 lv
...
