#How to create a tag
#0: "Number"
# - permission
# - "Tags"
0:
  - danhhieu.0
  - "§l§bмắт§aʙιếc"
1:
  - danhhieu.1
  - "§l§cＦＡ"
2:
  - danhhieu.2
  - "§l§cYOᑌ§dTᑌ§bᗷE"
3:
  - danhhieu.3
  - "§l§cʟovᴇʀ"
4:
  - danhhieu.4
  - "§l§bʙo§dss"
5:
  - danhhieu.5
  - "§l§aʙà§bтâɴ§cvʟoԍ"
6:
  - danhhieu.6
  - "§l§bмιɴᴇ§aғoʀᴇ"
7:
  - danhhieu.7
  - "§l§dɴнạт"
8:
  - danhhieu.8
  - "§l§cтʀùм§dsᴇʀvᴇʀ"
9:
  - danhhieu.9
  - "§l§6тʀầɴ§aтιԍᴇʀ"
10:
  - danhhieu.10
  - "§l§clʎɔɐn§asoldɹɐ"
11:
  - danhhieu.11
  - "§l§dғ§bᴀ§cu§as§eт"
12:
  - danhhieu.12
  - "§l§6ʏԍԍᴅʀᴀ§cғoʟιuм"
