# Config file for iProtector by LDX;

# Settings for unprotected areas in worlds without specific settings:
Default:

  # Keep players from getting hurt?
  God: false


# Settings for unprotected areas in individual worlds:
Worlds:

  skyblock:

    # Keep players from getting hurt?
    God: false

